language: go
go:
- 1.7.x
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
- go get github.com/mattn/goveralls
install:
- make clobber install
script:
- $HOME/gopath/bin/goveralls -service=travis-ci
env:
  global:
    secure: sxS8Jku0T98MnGPbHjrdfI0Hz5ejJmezc0zBJQ3sgCVLZBL7M1i4htJ9uA5fEVdw9+127SFG+PVKo1ZschA8scm0b3D/G7kOvllFFAbaTzpmPlqsN8EDFlqsdUhsWOvChSne7wQ7ssPbKWdeqnuwwkYT2BYWEGA0pepmv9fP1/fLCTz17VBZtUwHmyxFvr4hgm4BW6Dnf2rXQJFLkfbjDUkphKO1OtQzxnb6iKclQ8C8X1CFyMNuD15PUHHqFLkk+zGgBE3q1O2q9/whBzX5UXp/yN3+CI8IKY6GH5KRrdxpRDrLUKhvGEpWOpzDJMi8b1Dhs4JSYmrQU/nIrY57S/p738R9MtWTlzzpjTSONnv4E6AeilNFKaLUOuS4WuY6qBPGVNeYXy/ryEzCEGDt/jv/KmkdVHHSwePpCLD9sCQZ/tBJb2cYpCMZZOhdtk5olqPN1O6zRq0+IOtW64ZCUvZRheIm50b64VzfkSa7EVK4SXk9cZHlv8DYcwgRhmXchfv8LEsSag8XZYFB7DpSvVhWs0AjBsGbSS9DOfTkFqTvJSzVKiW3pDIInWlM36vgSh/0i2fyujKLAN5I3O6zqDbWirB1la1sVKCayHf60VX603M6LadHpHzDXMtgmeio2Ft3RtuI1FN4rjaXeLX7U9sgQ6Ke2j7Th3+Dxz3F3Mk=
